"""add daily_stats table

Revision ID: 57ed05573b96
Revises: 7581df69eee2
Create Date: 2025-07-05 04:50:31.107906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ed05573b96'
down_revision: Union[str, Sequence[str], None] = '7581df69eee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'status', name='uq_day_status')
    )
    op.create_index(op.f('ix_daily_stats_day'), 'daily_stats', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_stats_day'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
