"""create issues table

Revision ID: 7581df69eee2
Revises: adcd69bb2c3d
Create Date: 2025-07-05 04:24:59.864793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7581df69eee2'
down_revision: Union[str, Sequence[str], None] = 'adcd69bb2c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severityenum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'triaged', 'in_progress', 'done', name='statusenum'), nullable=False),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
